# Generated by Django 5.2.7 on 2026-01-06 00:08

import catalog.models
import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('names', models.JSONField(blank=True, default=dict)),
                ('descriptions', models.JSONField(blank=True, default=dict)),
                ('country', models.CharField(blank=True, max_length=2)),
                ('founded_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('icon_url', models.URLField(blank=True)),
                ('official_site_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discontinued', 'Discontinued'), ('hiatus', 'Hiatus')], default='active', max_length=16)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=64)),
                ('symbol', models.CharField(blank=True, max_length=8)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('synonyms', models.JSONField(blank=True, default=dict)),
                ('category', models.CharField(choices=[('construction', 'Construction'), ('accessory', 'Accessory'), ('trim', 'Trim'), ('attachment', 'Attachment')], default='construction', max_length=16)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('origin_country', models.CharField(blank=True, max_length=2)),
                ('production_country', models.CharField(blank=True, max_length=2)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1970), django.core.validators.MaxValueValidator(2100)])),
                ('release_date', models.DateField(blank=True, null=True)),
                ('collaboration', models.CharField(blank=True, max_length=255)),
                ('limited_edition', models.BooleanField(default=False)),
                ('has_matching_set', models.BooleanField(default=False)),
                ('verified_source', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('extra_metadata', models.JSONField(blank=True, default=dict)),
                ('product_number', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['brand__slug', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='ItemCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('mainline', 'Mainline'), ('special', 'Special'), ('collaboration', 'Collaboration')], default='mainline', max_length=16)),
            ],
            options={
                'ordering': ['item__slug', 'collection__name'],
            },
        ),
        migrations.CreateModel(
            name='ItemColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['item__slug', 'color__name'],
            },
        ),
        migrations.CreateModel(
            name='ItemFabric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['item__slug', 'fabric__name'],
            },
        ),
        migrations.CreateModel(
            name='ItemFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_prominent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['item__slug', 'feature__name'],
            },
        ),
        migrations.CreateModel(
            name='ItemMeasurement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_one_size', models.BooleanField(default=False)),
                ('bust_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hip_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('sleeve_length_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('hem_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('heel_height_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('bag_depth_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fit_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['item__slug'],
            },
        ),
        migrations.CreateModel(
            name='ItemMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(blank=True, max_length=64)),
                ('sleeve_type', models.CharField(blank=True, max_length=128)),
                ('season', models.CharField(blank=True, max_length=128)),
                ('fit', models.CharField(blank=True, max_length=128)),
                ('length', models.CharField(blank=True, max_length=128)),
                ('lining', models.CharField(blank=True, max_length=128)),
                ('closure_type', models.CharField(blank=True, max_length=128)),
                ('care_instructions', models.TextField(blank=True)),
                ('inspiration', models.TextField(blank=True)),
                ('ai_confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'ordering': ['item__slug'],
            },
        ),
        migrations.CreateModel(
            name='ItemPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('source', models.CharField(choices=[('origin', 'Origin'), ('converted', 'Converted'), ('manual', 'Manual')], default='origin', max_length=16)),
                ('rate_used', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recommendation', models.CharField(choices=[('recommend', 'Recommend'), ('not_recommend', 'Not recommend'), ('mixed', 'Mixed')], max_length=16)),
                ('body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('moderation_note', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_slug', models.SlugField(blank=True, max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_translations', models.JSONField(blank=True, default=list)),
                ('reference_url', models.URLField(blank=True)),
                ('reference_urls', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('name_translations', models.JSONField(blank=True, default=list)),
                ('release_year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('category_slug', models.SlugField(blank=True, max_length=128)),
                ('subcategory_slug', models.SlugField(blank=True, max_length=128)),
                ('style_slugs', models.JSONField(blank=True, default=list)),
                ('substyle_slugs', models.JSONField(blank=True, default=list)),
                ('color_slugs', models.JSONField(blank=True, default=list)),
                ('fabric_breakdown', models.JSONField(blank=True, default=list)),
                ('feature_slugs', models.JSONField(blank=True, default=list)),
                ('collection_reference', models.CharField(blank=True, max_length=255)),
                ('collection_proposal', models.JSONField(blank=True, default=dict)),
                ('size_measurements', models.JSONField(blank=True, default=list)),
                ('price_amounts', models.JSONField(blank=True, default=list)),
                ('origin_country', models.CharField(blank=True, max_length=2)),
                ('production_country', models.CharField(blank=True, max_length=2)),
                ('limited_edition', models.BooleanField(default=False)),
                ('has_matching_set', models.BooleanField(default=False)),
                ('verified_source', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('moderator_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemSubstyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'ordering': ['item__slug', 'substyle__name'],
            },
        ),
        migrations.CreateModel(
            name='ItemTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('context', models.CharField(choices=[('primary', 'Primary'), ('secondary', 'Secondary')], default='primary', max_length=16)),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
            ],
            options={
                'ordering': ['item__slug', 'tag__name'],
            },
        ),
        migrations.CreateModel(
            name='ItemTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dialect', models.CharField(blank=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('pattern', models.CharField(blank=True, max_length=255)),
                ('fit', models.CharField(blank=True, max_length=255)),
                ('length', models.CharField(blank=True, max_length=255)),
                ('season', models.CharField(blank=True, max_length=255)),
                ('lining', models.CharField(blank=True, max_length=255)),
                ('closure_type', models.CharField(blank=True, max_length=255)),
                ('care_instructions', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('official', 'Official'), ('ai', 'AI'), ('user', 'User')], default='user', max_length=16)),
                ('quality', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified')], default='draft', max_length=16)),
                ('auto_translated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['item__brand__slug', 'item__slug', 'language__code'],
            },
        ),
        migrations.CreateModel(
            name='ItemVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant_label', models.CharField(max_length=255)),
                ('sku', models.CharField(blank=True, max_length=255)),
                ('size_descriptor', models.CharField(blank=True, max_length=128)),
                ('stock_status', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('sold_out', 'Sold Out'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('notes', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['item__slug', 'variant_label'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('native_name', models.CharField(blank=True, max_length=128)),
                ('is_supported', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_file', models.ImageField(upload_to=catalog.models.review_image_upload_to)),
                ('storage_path', models.CharField(blank=True, max_length=512)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['category__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Substyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['style__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('style', 'Style'), ('detail', 'Detail'), ('material', 'Material'), ('motif', 'Motif'), ('construction', 'Construction')], default='detail', max_length=16)),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TagTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('official', 'Official'), ('ai', 'AI'), ('user', 'User')], default='user', max_length=16)),
                ('quality', models.CharField(choices=[('draft', 'Draft'), ('verified', 'Verified')], default='draft', max_length=16)),
                ('auto_translated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['tag__name', 'language__code'],
            },
        ),
        migrations.CreateModel(
            name='WardrobeEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('owned', 'Owned'), ('wishlist', 'Wishlist')], default='owned', max_length=16)),
                ('is_public', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('colors', models.JSONField(blank=True, default=list)),
                ('size', models.CharField(blank=True, max_length=64)),
                ('acquired_date', models.DateField(blank=True, null=True)),
                ('arrival_date', models.DateField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=3)),
                ('was_gift', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BrandStyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
            ],
            options={
                'ordering': ['brand__slug', 'style__name'],
            },
        ),
        migrations.CreateModel(
            name='BrandSubstyle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.brand')),
            ],
            options={
                'ordering': ['brand__slug', 'substyle__name'],
            },
        ),
        migrations.CreateModel(
            name='BrandTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.brand')),
            ],
            options={
                'ordering': ['brand__slug', 'language__code'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('season', models.CharField(blank=True, choices=[('spring', 'Spring'), ('summer', 'Summer'), ('fall', 'Fall'), ('winter', 'Winter'), ('resort', 'Resort')], max_length=16)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)])),
                ('description', models.TextField(blank=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='catalog.brand')),
            ],
            options={
                'ordering': ['brand__slug', '-year', 'season', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('hex_code', models.CharField(blank=True, max_length=7)),
                ('lch_values', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'hex_code')},
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('storage_path', models.CharField(blank=True, max_length=512)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to=catalog.models.image_upload_to)),
                ('type', models.CharField(choices=[('cover', 'Cover'), ('gallery', 'Gallery'), ('detail', 'Detail'), ('brand_logo', 'Brand Logo'), ('lookbook', 'Lookbook')], default='gallery', max_length=16)),
                ('caption', models.TextField(blank=True)),
                ('is_cover', models.BooleanField(default=False)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('file_size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('hash_signature', models.CharField(blank=True, max_length=255)),
                ('dominant_color', models.CharField(blank=True, max_length=7)),
                ('source', models.CharField(blank=True, max_length=32)),
                ('license', models.CharField(blank=True, max_length=255)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),

        migrations.AddField(
            model_name='image',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='item',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.brand'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_currency_items', to='catalog.currency'),
        ),
        migrations.AddField(
            model_name='item',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemcollection',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.collection'),
        ),
        migrations.AddField(
            model_name='itemcollection',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='items', through='catalog.ItemCollection', to='catalog.collection'),
        ),
        migrations.AddField(
            model_name='itemcolor',
            name='color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.color'),
        ),
        migrations.AddField(
            model_name='itemcolor',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='items', through='catalog.ItemColor', to='catalog.color'),
        ),
        migrations.AddField(
            model_name='itemfabric',
            name='fabric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.fabric'),
        ),
        migrations.AddField(
            model_name='itemfabric',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='fabrics',
            field=models.ManyToManyField(blank=True, related_name='items', through='catalog.ItemFabric', to='catalog.fabric'),
        ),
        migrations.AddField(
            model_name='itemfavorite',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemfavorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemfeature',
            name='feature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.feature'),
        ),
        migrations.AddField(
            model_name='itemfeature',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='items', through='catalog.ItemFeature', to='catalog.feature'),
        ),
        migrations.AddField(
            model_name='itemmeasurement',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemmetadata',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.currency'),
        ),
        migrations.AddField(
            model_name='itemprice',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemreview',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemreview',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemreview',
            name='moderated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_item_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemsubmission',
            name='linked_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_sources', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='itemsubstyle',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemtag',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemtranslation',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.color'),
        ),
        migrations.AddField(
            model_name='itemvariant',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='itemmeasurement',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='measurements', to='catalog.itemvariant'),
        ),
        migrations.AddField(
            model_name='image',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='catalog.itemvariant'),
        ),
        migrations.AddField(
            model_name='itemtranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.language'),
        ),
        migrations.AddField(
            model_name='item',
            name='default_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_language_items', to='catalog.language'),
        ),
        migrations.AddField(
            model_name='brandtranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand_translations', to='catalog.language'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.itemreview'),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_review_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='brandstyle',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.style'),
        ),
        migrations.AddField(
            model_name='brand',
            name='styles',
            field=models.ManyToManyField(blank=True, related_name='brands', through='catalog.BrandStyle', to='catalog.style'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.category'),
        ),
        migrations.AddField(
            model_name='item',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='catalog.subcategory'),
        ),
        migrations.AddField(
            model_name='substyle',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substyles', to='catalog.style'),
        ),
        migrations.AddField(
            model_name='itemsubstyle',
            name='substyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.substyle'),
        ),
        migrations.AddField(
            model_name='item',
            name='substyles',
            field=models.ManyToManyField(blank=True, related_name='items', through='catalog.ItemSubstyle', to='catalog.substyle'),
        ),
        migrations.AddField(
            model_name='brandsubstyle',
            name='substyle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.substyle'),
        ),
        migrations.AddField(
            model_name='brand',
            name='substyles',
            field=models.ManyToManyField(blank=True, related_name='brands', through='catalog.BrandSubstyle', to='catalog.substyle'),
        ),
        migrations.AddField(
            model_name='itemtag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='items', through='catalog.ItemTag', to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='tagtranslation',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.language'),
        ),
        migrations.AddField(
            model_name='tagtranslation',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='catalog.tag'),
        ),
        migrations.AddField(
            model_name='wardrobeentry',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_entries', to='catalog.item'),
        ),
        migrations.AddField(
            model_name='wardrobeentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('brand', 'name', 'season', 'year')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcollection',
            unique_together={('item', 'collection')},
        ),
        migrations.AlterUniqueTogether(
            name='itemcolor',
            unique_together={('item', 'color')},
        ),
        migrations.AlterUniqueTogether(
            name='itemfabric',
            unique_together={('item', 'fabric')},
        ),
        migrations.AlterUniqueTogether(
            name='itemfavorite',
            unique_together={('user', 'item')},
        ),
        migrations.AlterUniqueTogether(
            name='itemfeature',
            unique_together={('item', 'feature')},
        ),
        migrations.AlterUniqueTogether(
            name='itemprice',
            unique_together={('item', 'currency', 'source')},
        ),
        migrations.AddConstraint(
            model_name='itemreview',
            constraint=models.UniqueConstraint(fields=('item', 'author'), name='unique_item_review_per_author'),
        ),
        migrations.AlterUniqueTogether(
            name='itemtranslation',
            unique_together={('item', 'language', 'dialect')},
        ),
        migrations.AlterUniqueTogether(
            name='brandtranslation',
            unique_together={('brand', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='brandstyle',
            unique_together={('brand', 'style')},
        ),
        migrations.AlterUniqueTogether(
            name='subcategory',
            unique_together={('category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='substyle',
            unique_together={('style', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='itemsubstyle',
            unique_together={('item', 'substyle')},
        ),
        migrations.AlterUniqueTogether(
            name='brandsubstyle',
            unique_together={('brand', 'substyle')},
        ),
        migrations.AlterUniqueTogether(
            name='tagtranslation',
            unique_together={('tag', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='wardrobeentry',
            unique_together={('user', 'item')},
        ),
    ]
