# Generated by Django 5.2.7 on 2026-01-16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_ingestion_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingestionjob",
            name="brand_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="ingestionjob",
            name="brand_slug",
            field=models.SlugField(blank=True, max_length=255),
        ),
    ]
