# Generated by Django 5.2.7 on 2025-10-31 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_style_alter_substyle_options_alter_substyle_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='substyle',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substyles', to='catalog.style'),
        ),
    ]
