# Generated by GitHub Copilot on 2026-01-16
from __future__ import annotations

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("maintenance_message", models.TextField(blank=True)),
            ],
            options={
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
